#include <cstdint>
#include <iostream>

#define PMAX 512

std::string pad_comma(uint16_t x) {
    std::string str = std::to_string(x);
    str = str + ",";
    int spaces = 5 - str.length();
    for(int j = 0; j < spaces; j++) str = str + " ";
    return str;
}

std::string pad(uint16_t x) {
    std::string str = std::to_string(x);
    int spaces = 5 - str.length();
    for(int j = 0; j < spaces; j++) str = str + " ";
    return str;
}

int main() {
    uint16_t p,a,b;
    uint16_t inverse[PMAX][PMAX];
    bool prime[PMAX];
    int numzeros;
    for(p = 0; p < PMAX; p++) {
        for(a = 0; a < PMAX; a++) {
            inverse[p][a] = 0;
            for(b = 0; b < p; b++) if((a * b)%p == 1) inverse[p][a] = b;
        }
        numzeros = 0;
        for(a = 0; a < p; a++) if(inverse[p][a] == 0) numzeros++;
        prime[p] = false;
        if(numzeros == 1) prime[p] = true;
    }
    std::cout << "#ifndef MODPINVERSE_HPP\n";
    std::cout << "#define MODPINVERSE_HPP\n\n";
    std::cout << "#define PMAX 512\n\n"; 
    std::cout << "//This header has been automatically generated by generate_inverses.cpp\n\n";
    std::cout << "#include <cstdint>\n\n";
    std::cout << "//if p is prime then p_prime[p] == true\n";
    std::cout << "const static bool p_prime[" << PMAX << "] = {\n";
    for(p = 0; p < PMAX; p++) {
        if(prime[p]) std::cout << "\ttrue,  //" << p << "\n";
        else std::cout << "\tfalse, //" << p << "\n";
    }
    std::cout << "};\n\n";
    std::cout << "//p_inverse[p][x] is the inverse mod p of x, if it exists, otherwise zero\n";
    std::cout << "const static uint16_t p_inverse[" << PMAX << "][" << PMAX << "] = {\n";
    for(p = 0; p < PMAX; p++) {
        std::cout << "\t{\n";
        for(a = 0; a < PMAX; a++) {
            if(a < PMAX-1) std::cout << "\t" << pad_comma(inverse[p][a]) << "//[" << p <<"][" << a << "]\n";
            else std::cout << "\t" << pad(inverse[p][a]) << "//[" << p <<"][" << a << "]\n";
        }
        if(p < PMAX-1) std::cout << "\t},\n";
        else std::cout << "\t}\n";
    }
    std::cout << "};\n\n";
    std::cout << "#endif" << std::endl;
    return 0;
}